#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

# Configure Nginx to listen on port 80
sudo sed -i 's/listen \[::\]:80 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

# Add "Hello WOrld!" to the default page
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null


# start Nginx
sudo service nginx start
