#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

echo "Hello World!" >> /var/www/html/index.html

sudo sed -i 's/server_name _;/server_name _;\n\n\tlocation \/redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}/' /etc/nginx/sites-available/default

# restart Nginx
sudo service nginx restart
