#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

echo "Hello World!" >> /var/www/html/index.html

sudo sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;/" /etc/nginx/sites-available/default

# start Nginx
sudo service nginx start
