#!/usr/bin/env bash

# Install Nginx
sudo apt update
sudo apt install -y nginx

echo "Ceci n'est pas une page" >> /usr/share/nginx/html/custom_404.html
sudo sed -i 's|try_files \$uri \$uri/ =404;|error_page 404 /custom_404.html;\nlocation=/custom_404.html {\ninternal;\n root/usr/share/nginx/html;\n}|' /etc/nginx/sites-available/default
# start Nginx
sudo service nginx start
